data:
  path: "data/housing_price_dataset.csv"
model:
  test_size: 0.3
  random_state: 42
  encode_columns: 'Neighborhood'
  target_column: 'Price'
  save_path: 'model.joblib'
save_names:
  target: 'data/target.csv'
  features: 'data/test.csv'
